### ISSUE TITLE
Vector layer: label not shown

### ISSUE THREAD

**Issue by muellerflorian** [imjoy-team/kaibu#60]
In the previous version of Kaibu, the label of a vector label was shown centered in the outlined polygon, e.g. `cells`. 

In the current version, this doesn't seem to be the case anymore.

**Comment by oeway** [comment]
Hi, yes, this is now controlled by a config, you can show it by setting called text_placement.

See here: https://kaibu.org/docs/#/api?id=add_shapesshapes-options

**Comment by muellerflorian** [comment]
Excellent. Thanks!
