### ISSUE TITLE
Image display dimmed with opened sidebar

### ISSUE THREAD

**Issue by muellerflorian** [imjoy-team/kaibu#61]
Seems that the image display is dimmed with the side-bar being open (see below). This makes adjustments in the image more tedious since their effects can only be judged after closing the side-bar. 

side-bar open:
![image](https://user-images.githubusercontent.com/10832779/108366230-6bd6cf00-71f8-11eb-89cd-3307a216d225.png)

side-bar closed:
![image](https://user-images.githubusercontent.com/10832779/108366381-988ae680-71f8-11eb-97c4-bcb2c3eb22ca.png)

**Comment by muellerflorian** [comment]
update. this actually ony occurs when the sidebar overlaps with the image. if there is enough space next to the image for the side-bar to be shown, all is good. 

![kaibu-resize](https://user-images.githubusercontent.com/10832779/108380162-e3135f80-7206-11eb-94a6-d91aef6b091b.gif)

**Comment by oeway** [comment]
Yes, this was the design, we switch on the so-called `overlay` mode when the screen width < 800pixels. I will remove this.
